---
collections:
  - name: community.routeros
  - name: community.general
  - name: community.sops
  - name: ansible.netcommon
  - name: ansible.posix  # synchronize (rsync also needed on controller + host)
